### PR TITLE
Make relative links absolute

### PR DESCRIPTION
**Pull request by richard-still-ft**

### CODE REVIEW

**Comment by quarterto** [comment]
I think I've seen some relative stream page links, let me see if I can find some

**Comment by quarterto** [comment]
http://amp.ft.com/content/94e97eee-ce9a-11e5-831d-09f7778e7377

**Comment by quarterto** [comment]
The Next link rewrites: https://github.com/Financial-Times/next-article/blob/master/server/transforms/relative-links.js

**Comment by richard-still-ft** [comment]
@quarterto

**Comment by quarterto** [comment]
:+1:

**Pull request merged**
