### PR TITLE
Live blogs AT-377

### PR DESCRIPTION
**Pull request by quarterto**

### CODE REVIEW

**Comment by quarterto** [comment]
I've added a rudimentary in-memory cache for the live blogs calls. When a user requests a live blog the server starts polling Blogs every 5 seconds to keep its cache fresh, and all subsequent requests hit only the cache. The server stops polling and evicts the cache for a URL after 20 seconds, so the 15 second user poll will keep the server polling while at least one user is viewing the blog.

I've tested this for consistency, using simultaneous users on the same and different live blogs, and I'm reasonably confident about it. We should keep an eye on memory usage but a long-running live blog should reach only about 50k heap. I'm more worried about leaking timeouts but it should be fine.

**Comment by georgecrawford** [comment]
1. Rebase please
2. I'm seeing `<span class="live-blog--author live-blog--author-colour-NaN">`

**Comment by georgecrawford** [comment]
https://ft-google-amp-staging-pr-172.herokuapp.com/content/85c7c9eb-3f8f-3a55-9a62-eccd4319d1ac with live blog override `c8bt1rza` gave:

```
TypeError: Cannot convert undefined or null to object
   at edits.forEach (/app/server/lib/live-blogs/collate-messages.js:23:10)
   at Array.forEach (native)
   at module.exports (/app/server/lib/live-blogs/collate-messages.js:22:8)
   at module.exports (/app/server/lib/live-blogs/render.js:24:34)
   at Promise.resolve.then.data (/app/server/lib/live-blogs/get-live-blog.js:78:10)
   at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

Log of events:
Messages & events
- updated title to "George's test blog" and excerpt to "Here's George's amazing excerpt! "

- G 10/18/2016, 4:45:42 PM
`hello!`

- G 10/18/2016, 4:46:35 PM
`this live blog is now in progress`

- george 10/18/2016, 4:46:54 PM
`what changed?`

- G 10/18/2016, 4:45:42 PM edited message 1
`hello - oops, correction!`

**Comment by quarterto** [comment]
Fixed that error, it happens when a message that's before the filter timestamp gets edited

**Pull request merged**
