### PR TITLE
Add a GTG check for the GLB

### PR DESCRIPTION
**Pull request by richard-still-ft**

### CODE REVIEW

**Comment by rowanbeentje** [comment]
Can I suggest adding https://github.com/Financial-Times/express-web-service ?  Available in npm as `express-ftwebservice`, also handles about etc fairly easily

**Comment by quarterto** [comment]
+1 for express-web-service

**Comment by richard-still-ft** [comment]
Makes sense

**Comment by quarterto** [comment]
Can we add `appVersion: process.env.HEROKU_RELEASE_VERSION`?

**Comment by quarterto** [comment]
Actually there's a bunch more data from https://docs.google.com/document/d/1B80a0nAI8L1cuIlSEai4Zuztq7Lef0ytxJYNFCjG7Ko/edit# we'll want to add e.g. `contacts`, `links`

**Pull request merged**
