### PR TITLE
don't follow redirects in get-stream-url

### PR DESCRIPTION
**Pull request by quarterto**
by default, node-fetch follows redirects. ft.com immediately returns a 302 for stream pages that exist, so node-fetch redirects and loads the actual topic page.

### CODE REVIEW

**Comment by georgecrawford** [comment]
@quarterto That actually broke all the streamUrls. This is the only way I think we can do it without https://github.com/bitinn/node-fetch/pull/67 by some @matthew-andrews guy. Otherwise we could similarly resort to a shell `curl` command.

**Comment by matthew-andrews** [comment]
the `follow` option in node-fetch doesn't really do anything useful.  also i think if you look through the github repo there are some reasons why bitinn has rejected things like https://github.com/bitinn/node-fetch/pull/84 before.

**Comment by matthew-andrews** [comment]
this file may interest you :grin: 
https://github.com/Financial-Times/next-falcon-redirect/blob/bc3ab9db84fb865063f08778388a89a07c56922e/server/lib/falcon-url-guess-probe.js#L27

**Comment by georgecrawford** [comment]
Thanks for the link. That's some of the best JavaScript I've seen.

**Comment by matthew-andrews** [comment]
doh!  hahahahah

**Comment by quarterto** [comment]
[`@quarterto/fetch-head`](https://gist.github.com/quarterto/641635c0f3017541438e)

**Comment by georgecrawford** [comment]
cc @matthew-andrews ^^

**Comment by matthew-andrews** [comment]
you should totes publish that to npm

**Comment by quarterto** [comment]
it is! https://www.npmjs.com/package/@quarterto/fetch-head

(I have a script that publishes gists to npm: https://github.com/quarterto/gist-publish-npm)

**Comment by georgecrawford** [comment]
Guys, be aware it doesn't currently work :)

**Comment by georgecrawford** [comment]
I'm in the middle of debugging why.

**Comment by matthew-andrews** [comment]
shipit

**Comment by quarterto** [comment]
LGTM!

**Pull request merged**
