### PR TITLE
Fix path to env file

### PR DESCRIPTION
**Pull request by georgecrawford**

### CODE REVIEW

**Comment by quarterto** [comment]
unfortunately `.env` isn't quite in a format you can `source` (the node module doesn't [support `export`](https://github.com/motdotla/dotenv/pull/118)).

**Comment by quarterto** [comment]
there is https://github.com/adjohnson916/dotenv-export

**Comment by quarterto** [comment]
by the way the build failure is fixed in https://github.com/Financial-Times/google-amp/pull/108/commits/6942cf94917b21d57178f734f9a97f54ca52a353, i'll cherry pick that and open a pr

**Comment by georgecrawford** [comment]
See https://github.com/Financial-Times/google-amp/pull/115

**Pull request closed without merging**
