### PR TITLE
Access mock

### PR DESCRIPTION
**Pull request by georgecrawford**
NB: requires you to run `AMP.toggleExperiment('amp-access-analytics')` in the browser to toggle the experiment flag.

### CODE REVIEW

**Comment by quarterto** [comment]
> requires you to run `AMP.toggleExperiment('amp-access-analytics')`

eww

**Comment by mclarke47** [comment]
We've put the amp-access-svc behind the AWS API Gateway so it might make sense to use the hostname that goes there: amp-access-svc-lb-eu-west-1-prod.memb.ft.com instead of the one that goes straight to the application servers?

**Comment by adaybujeda** [comment]
Lets leave the current end-points. They are load balanced between UK and US (4 boxes), just is case they are needed.

**Comment by georgecrawford** [comment]
Replacing this with https://github.com/Financial-Times/google-amp/pull/44

**Pull request closed without merging**
